### ISSUE TITLE
我用fiddle抓不到美团数据，找不到城市id，请求帮助

### ISSUE THREAD

**Issue by MaNongXiaoGang** [hahaha108/meituanAppSpider#12]
感谢博主的分享，对我有很大帮助。能否再写一篇博客，讲述一下怎么抓到数据包的。这个问题困扰我很久了。

**Comment by YiranJing** [comment]
我也想知道，如何得到城市ID，我想抓取郑州的餐厅数据

**Comment by hahaha108** [comment]
最简单方法，打开https://www.meituan.com/，查看网页源码，AppData里有城市ID
