### ISSUE TITLE
请问一下城市的id是在哪里抓包的?

### ISSUE THREAD

**Issue by Rockyzsu** [hahaha108/meituanAppSpider#3]
感谢楼主博主写的文章,不过请问下城市的id是从哪里获取的?

**Comment by kyuubeeSama** [comment]
我是用手机app抓包，通过分析一些接口拼接的cid来判断的，切换城市，cid也会跟着改变

**Comment by pinkanguser** [comment]
> 我是用手机app抓包，通过分析一些接口拼接的cid来判断的，切换城市，cid也会跟着改变

大神，能否分享一下城市cid，我用fiddler抓不到包

**Comment by wlj2cat** [comment]
你是从什么地方得到我信息的？


 
---原始邮件---
发件人: "pinkanguser"<notifications@github.com>
发送时间: 2019年7月17日(星期三) 上午9:36
收件人: "hahaha108/meituanAppSpider"<meituanAppSpider@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [hahaha108/meituanAppSpider] 请问一下城市的id是在哪里抓包的? (#3)


 
我是用手机app抓包，通过分析一些接口拼接的cid来判断的，切换城市，cid也会跟着改变
  
大神，能否分享一下城市cid，我用fiddler抓不到包

**Comment by kyuubeeSama** [comment]
> > 我是用手机app抓包，通过分析一些接口拼接的cid来判断的，切换城市，cid也会跟着改变
> 
> 大神，能否分享一下城市cid，我用fiddler抓不到包

我用的是charles.现在https的我也看不到，我是根据仅有的几个http链接里面分析链接的。里面有个链接host是http://apimobile.meituan.com。他的get请求地址里面有一个参数是ci，ci=1是北京，ci=10上海。手机app切换地址，这个链接也会重新请求，就可以获取到ci了

**Comment by Rockyzsu** [comment]
这个在美团页面里面找到的
